#!/bin/sh
# Copy all configuration files from $FROM" to this repository.
FROM="$1"
INTO="${2:-.}"
cd `dirname "$0"` || exit $?
mkdir -p\
      "$INTO"/etc/apache2\
      "$INTO"/etc/dovecot\
      "$INTO"/etc/getmail\
      "$INTO"/etc/ldap\
      "$INTO"/etc/ldapcherry\
      "$INTO"/etc/logrotate.d\
      "$INTO"/etc/postfix\
      "$INTO"/etc/roundcube\
      "$INTO"/etc/systemd/system\
      "$INTO"/usr/share/ldapcherry\
      "$INTO"/usr/share/roundcube\
      "$INTO"/var/www/html

cp -pr "$FROM"/etc/apache2/sites-available "$INTO"/etc/apache2/
cp -pr "$FROM"/etc/apache2/sites-enabled "$INTO"/etc/apache2/
cp -pr "$FROM"/etc/dovecot/*   "$INTO"/etc/dovecot/
cp -pr "$FROM"/etc/getmail/*   "$INTO"/etc/getmail/
cp -pr "$FROM"/etc/ldap/*      "$INTO"/etc/ldap/
cp -pr "$FROM"/etc/ldapcherry/* "$INTO"/etc/ldapcherry/
cp -p  "$FROM"/etc/logrotate.d/getmail "$INTO"/etc/logrotate.d/
cp -pr "$FROM"/etc/postfix/*   "$INTO"/etc/postfix/
cp -pr "$FROM"/etc/roundcube/* "$INTO"/etc/roundcube/
cp -pr "$FROM"/usr/share/ldapcherry/* "$INTO"/usr/share/ldapcherry
cp -pr "$FROM"/usr/share/roundcube/* "$INTO"/usr/share/roundcube
cp -pr "$FROM"/etc/systemd/system/getmail.service "$INTO"/etc/systemd/system/
cp -pr "$FROM"/etc/systemd/system/ldapcherry.service "$INTO"/etc/systemd/system/
cp -pr "$FROM"/var/www/html/*   "$INTO"/var/www/html/

# Don't backup files that contain sensitive information, e.g. passwords.
# Don't backup files that should not be deployed.
rm -f "$INTO"/etc/dovecot/dovecot-users
rm -f "$INTO"/etc/dovecot/dovecot-ldap.conf.ext
rm -f "$INTO"/etc/dovecot/ldap-password.txt
rm -f "$INTO"/etc/dovecot/users
rm -f "$INTO"/etc/getmail/*.password
rm -f "$INTO"/etc/getmail/oldmail-*
rm -f "$INTO"/etc/ldap/admin-password.txt
rm -rf "$INTO"/etc/ldap/slapd.d/cn=config
rm -f "$INTO"/etc/ldap/slapd.d/cn=config.ldif
rm -f "$INTO"/etc/ldapcherry/ldapcherry.ini
rm -f "$INTO"/etc/postfix/post-install
rm -f "$INTO"/etc/postfix/postfix-files
rm -f "$INTO"/etc/postfix/postfix-script
rm -f "$INTO"/etc/postfix/sasl_passwd
find "$INTO"/usr/share/roundcube -type f \( -name '*.gif' -o -name '*.png' -o -name '*.svg' \) \
    | xargs -d '\n' rm -f
