#!/bin/sh
# Compare configuration files with this repository.
# The output shows the effect that ./deploy would have.
FROM="$1"
TO="${2:-.}"
[ $# -gt 0 ] && shift
[ $# -gt 0 ] && shift
# The shifts enable "$@" to be passed as options to diff (below).
cd `dirname "$0"` || exit $?
# echo "FROM=$FROM" "TO=$TO"
for FILE in \
    `find "$TO"/etc "$TO"/usr "$TO"/var -type f | sed -e "s:^$TO/::" | grep -v '~$' | grep -v '^etc/postfix/.*\.db$'`
do
    # echo "FILE=$FILE"
    if [ -e "$FROM"/"$FILE" ]; then
        diff > /dev/null 2>&1 "$FROM"/"$FILE" "$TO"/"$FILE" || {
	    echo
	    echo diff "$@" "$FROM"/"$FILE" "$TO"/"$FILE"
            diff 2>&1 "$@" "$FROM"/"$FILE" "$TO"/"$FILE"
        }
    elif [ -e `dirname "$FROM"/"$FILE"` ]; then
        echo
        echo "new file:" "$FROM"/"$FILE"
    fi
done
for TEMPLATE in\
    "$TO"/etc/dovecot/*.template\
    "$TO"/etc/ldapcherry/*.template\
; do
    FILE=`echo "$TEMPLATE" | sed -e "s:^$TO/::" | sed -e 's/\.template$//'`
    ./expand "$TEMPLATE" | diff > /dev/null 2>&1 "$FROM"/"$FILE" - || {
	echo
	echo diff "$@" "$FROM"/"$FILE" '`'"expand $TEMPLATE"'`'
        ./expand "$TEMPLATE" | diff 2>&1 "$@" "$FROM"/"$FILE" -
    }
done
