#!/bin/sh
# Copy all configuration files from this repository to $INTO.
INTO="$1"
cd `dirname "$0"` || exit $?
for FILE in `find etc -type f | grep -v '~$' | grep -v '^etc/postfix/.*\.db'`; do
    diff > /dev/null 2>&1 "$FILE" "$INTO"/"$FILE" || {
	echo cp -p "$FILE" "$INTO"/"$FILE"
	cp -p "$FILE" "$INTO"/"$FILE"
    }
done
postmap "$INTO"/etc/postfix/sasl_passwd
postmap "$INTO"/etc/postfix/transport
postmap "$INTO"/etc/postfix/virtual_mailbox_domains
